# Generated by Django 5.0 on 2026-09-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام ژانر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('color', models.CharField(default='#D4A574', max_length=20, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('completed', 'تمام\u200cشده'), ('archived', 'بایگانی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('total_segments', models.PositiveIntegerField(default=0, verbose_name='تعداد ادامه\u200cها')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='کل رأی\u200cها')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.genre', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'داستان',
                'verbose_name_plural': 'داستان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='متن')),
                ('votes', models.IntegerField(default=0, verbose_name='رأی\u200cها')),
                ('is_canon', models.BooleanField(default=False, verbose_name='ادامه رسمی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stories.segment', verbose_name='ادامه قبلی')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='stories.story', verbose_name='داستان')),
            ],
            options={
                'verbose_name': 'ادامه',
                'verbose_name_plural': 'ادامه\u200cها',
                'ordering': ['-votes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رأی')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='stories.segment', verbose_name='ادامه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رأی',
                'verbose_name_plural': 'رأی\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['story', 'is_canon'], name='stories_seg_story_i_4b03e3_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['story', 'parent'], name='stories_seg_story_i_570efa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'segment')},
        ),
    ]
