# Generated by Django 5.0 on 2026-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='کاور'),
        ),
    ]
