# Generated by Django 5.0 on 2026-09-24 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, help_text='خلاصه\u200cای که توی لیست پست\u200cها نشون داده می\u200cشه', max_length=300, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='کاور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
