# Generated by Django 5.0 on 2026-09-24 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'داستان'), ('segment', 'ادامه'), ('user', 'کاربر')], max_length=20, verbose_name='نوع محتوا')),
                ('reason', models.CharField(choices=[('spam', 'اسپم'), ('abuse', 'توهین و آزار'), ('inappropriate', 'محتوای نامناسب'), ('copyright', 'نقض حق تکثیر'), ('misinformation', 'اطلاعات نادرست'), ('other', 'دلیل دیگر')], max_length=20, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی\u200cشده'), ('resolved', 'حل\u200cشده'), ('rejected', 'رد\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.segment')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.story')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx')],
            },
        ),
    ]
